export const ConcurrencyActionType = {
    SET_COMMON_CONCURRENCY: "SET-COMMON-CONCURRENCY",
    UPDATE_COMMON_CONCURRENCY: "UPDATE-COMMON-CONCURRENCY",
    REMOVE_COMMON_CONCURRENCY: 'REMOVE-COMMON-CONCURRENCY'
}