export class  PODetails  {
    ProjectDetails: [
        { title: 'RFQ No', value: 'RFQ no 01' },
        { title: 'Final REV No', value: 'Final REV No 02' },
        { title: 'Project ID', value: 'Project ID 01' },
        { title: 'Project Name', value: 'Project Name 01' },
        { title: 'Buyer’s Name', value: 'Buyer’s Name 01' },
        { title: 'PR No', value: 'PR No 01' },
    ];
    HeaderInformation: [
        {
            SupplierID: 'SID 5756757',
            SupplierNo: '1',
            CompanyName: 'ABC Corporation',
            ContactPerson: 'Mr. M Ali',
            PONo: 'TBC',
            Status: 'TBC',
            Currency: 'SAR',
            SupplierName: 'Consortium Of Branch Of Sinohydro',
        },

        {
            SupplierID: 'SID 5756767',
            SupplierNo: '2',
            CompanyName: 'BCD Corporation',
            ContactPerson: 'Mr. A Rahman',
            PONo: 'TBC',
            Status: 'TBC',
            Currency: 'LKR',
            SupplierName: 'Consortium Of Branch Of ABC',
        },

        {
            SupplierID: 'SID 5756777',
            SupplierNo: '3',
            CompanyName: 'GFD Corporation',
            ContactPerson: 'Mr. M Nauman',
            PONo: 'TBC',
            Status: 'TBC',
            Currency: 'AU',
            SupplierName: 'Consortium Of Branch Of GFD',
        },
    ];

    LinesInformation: [
        {
            SupplierID: 'SID 5756757',
            SupplierNo: '1',
            CompanyName: 'ABC Corporation',
            ContactPerson: 'Mr. M Ali',
            LinesDetails: [
                {
                    LineNo: '1',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Mat. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295422284.77',
                    NetAmtBase: '295422284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '3 months',
                    RentalDurationUoM: '2 months',
                    ChargeableDays: '20',
                },
        
                {
                    LineNo: '2',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Const. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295,422,284.77',
                    NetAmtBase: '295,422,284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '11/05/2022',
                    RentalDurationUoM: '11/05/2022',
                    ChargeableDays: '11/05/2022',
                },
                {
                    LineNo: '3',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Mat. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295,422,284.77',
                    NetAmtBase: '295,422,284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '11/05/2022',
                    RentalDurationUoM: '11/05/2022',
                    ChargeableDays: '11/05/2022',
                },
            ],
        },

        {
            SupplierID: 'SID 5756767',
            SupplierNo: '2',
            CompanyName: 'BCD Corporation',
            ContactPerson: 'Mr. A Rahman',
            LinesDetails: [
                {
                    LineNo: '1',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Mat. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295422284.77',
                    NetAmtBase: '295422284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '3 months',
                    RentalDurationUoM: '2 months',
                    ChargeableDays: '20',
                },
        
                {
                    LineNo: '2',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Const. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295,422,284.77',
                    NetAmtBase: '295,422,284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '11/05/2022',
                    RentalDurationUoM: '11/05/2022',
                    ChargeableDays: '11/05/2022',
                },
                {
                    LineNo: '3',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Mat. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295,422,284.77',
                    NetAmtBase: '295,422,284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '11/05/2022',
                    RentalDurationUoM: '11/05/2022',
                    ChargeableDays: '11/05/2022',
                },
            ],
        },

        {
            SupplierID: 'SID 5756777',
            SupplierNo: '3',
            CompanyName: 'GFD Corporation',
            ContactPerson: 'Mr. M Nauman',
            LinesDetails: [
                {
                    LineNo: '1',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Mat. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295422284.77',
                    NetAmtBase: '295422284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '3 months',
                    RentalDurationUoM: '2 months',
                    ChargeableDays: '20',
                },
        
                {
                    LineNo: '2',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Const. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295,422,284.77',
                    NetAmtBase: '295,422,284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '11/05/2022',
                    RentalDurationUoM: '11/05/2022',
                    ChargeableDays: '11/05/2022',
                },
                {
                    LineNo: '3',
                    PartNo: 'S0501010200000000001',
                    PartDiscription: 'P4-LSPB JV contract SAPMT Mat. Price',
                    POQty: '295422284.77',
                    PurchaseUOM: 'AU',
                    UnitpriceCurrency: 'AED',
                    Unitprice1: '1',
                    PriceUoM: 'AU',
                    UnitPriceBaseCurrency: 'SAR',
                    Unitprice2: '1',
                    NetAmtCurr: '295,422,284.77',
                    NetAmtBase: '295,422,284.77',
                    Discount: '0%',
                    AdditionalCost: '100.00',
                    PromisedDeliveryDate: '11/05/2022',
                    ProjectID: 'CAP-AM-01',
                    DestinationWarehouseID: 'WarehouseID-01',
                    PlannedRentalStartDate: '11/05/2022',
                    PlannedRentalDuration: '11/05/2022',
                    RentalDurationUoM: '11/05/2022',
                    ChargeableDays: '11/05/2022',
                },
            ],
        },
    ];

    

    PaymentDetails: [
        {
            SupplierID: 'SID 5756757',
            SupplierNo: '1',
            CompanyName: 'ABC Corporation',
            ContactPerson: 'Mr. M Ali',
            PONo: 'TBC',
            SupplierName: 'Consortium of Branch of Sinohydro',
            Site: 'C10113',
            Currency: 'SAR',
            PaymentTerm: 'Immediate - Due Immediately',
            TotalGrossAmtCurr: '52,116,624.66',
            TotalInclChargeCurr: '1.959,793,226.87',
            Planned: '217,103,564.90',

            table: [
                {
                    id: 'id 1',
                    des: 'des 1',
                },

                {
                    id: 'id 2',
                    des: 'des 2',
                },
            ],
        },

        {
            SupplierID: 'SID 5756767',
            SupplierNo: '2',
            CompanyName: 'BCD Corporation',
            ContactPerson: 'Mr. A Rahman',
            PONo: 'TBC',
            SupplierName: 'Consortium of Branch of Sinohydro',
            Site: 'C10223',
            Currency: 'SAR',
            PaymentTerm: 'Immediate - Due Immediately',
            TotalGrossAmtCurr: '52,116,624.66',
            TotalInclChargeCurr: '1.959,793,226.87',
            Planned: '217,103,564.90',
            table: [
                {
                    id: 'id 3',
                    des: 'des 3',
                },

                {
                    id: 'id 4',
                    des: 'des 4',
                },
            ],
        },

        {
            SupplierID: 'SID 5756777',
            SupplierNo: '3',
            CompanyName: 'GDF Corporation',
            ContactPerson: 'Mr. M Nauman',
            PONo: 'TBC',
            SupplierName: 'Consortium of Branch of Sinohydro',
            Site: 'C10223',
            Currency: 'SAR',
            PaymentTerm: 'Immediate - Due Immediately',
            TotalGrossAmtCurr: '52,116,624.66',
            TotalInclChargeCurr: '1.959,793,226.87',
            Planned: '217,103,564.90',
            table: [
                {
                    id: 'id 5',
                    des: 'des 5',
                },

                {
                    id: 'id 6',
                    des: 'des 6',
                },
            ],
        },
    ];

    Miscellaneous: [
        {
            SupplierID: 'SID 5756757',
            SupplierNo: '1',
            CompanyName: 'ABC Corporation',
            ContactPerson: 'Mr. M Ali',
            DeliveryAddress: '01 - Consortium Of Branch Of Sinohydro',
            OutputType: 'PO',
            Description:
                'PO is revised after reducing the amount that was already recieved in SAP',
            OutputType1: 'L1',
            Description1: 'L1',
            OutputType2: 'L2',
            Description2: 'L2',
        },

        {
            SupplierID: 'SID 5756767',
            SupplierNo: '2',
            CompanyName: 'BCD Corporation',
            ContactPerson: 'Mr. A Rahman',
            DeliveryAddress: '01 - Consortium Of Branch Of Sinohydro',
            OutputType: 'PO',
            Description:
                'PO is revised after reducing the amount that was already recieved in SAP',
            OutputType1: 'L1',
            Description1: 'L1',
            OutputType2: 'L2',
            Description2: 'L2',
        },

        {
            SupplierID: 'SID 5756777',
            SupplierNo: '3',
            CompanyName: 'GFD Corporation',
            ContactPerson: 'Mr. M Nauman',
            DeliveryAddress: '01 - Consortium Of Branch Of Sinohydro',
            OutputType: 'PO',
            Description:
                'PO is revised after reducing the amount that was already recieved in SAP',
            OutputType1: 'L1',
            Description1: 'L1',
            OutputType2: 'L2',
            Description2: 'L2',
        },
    ];
};


